name: hover_zoom_image
description: "A Flutter widget that provides a hover-to-zoom effect on images."
version: 0.0.1
homepage: "https://github.com/CodeBySubin/hover_zoom_image"
repository: "https://github.com/CodeBySubin/hover_zoom_image"
issue_tracker: "https://github.com/CodeBySubin/hover_zoom_image/issues"
environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: HoverZoomPlugin
        fileName: hover_zoom_plugin_web.dart
